part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const AUTH = _Paths.AUTH;
  static const MESSAGE = _Paths.MESSAGE;
  static const CONDITION = _Paths.CONDITION;
  static const MES_MESSAGES = _Paths.MES_MESSAGES;
  static const ALL_MESSAGES = _Paths.ALL_MESSAGES;
  static const ADD_MESSAGE = _Paths.ADD_MESSAGE;
  static const EDIT_MESSAGE = _Paths.EDIT_MESSAGE;
  static const ALERTE = _Paths.ALERTE;
  static const MES_ALERTES = _Paths.MES_ALERTES;
  static const ALL_ALERTES = _Paths.ALL_ALERTES;
  static const ADD_ALERTE = _Paths.ADD_ALERTE;
  static const EDIT_ALERTE = _Paths.EDIT_ALERTE;
  static const ACTUALITE = _Paths.ACTUALITE;
  static const AGENDA = _Paths.AGENDA;
  static const COMMERCE = _Paths.COMMERCE;
  static const SHOW_COMMERCE = _Paths.SHOW_COMMERCE;
  static const SHOW_ACTUALITE = _Paths.SHOW_ACTUALITE;
  static const SHOW_AGENDA = _Paths.SHOW_AGENDA;
  static const SHOW_ALERTE = _Paths.SHOW_ALERTE;
  static const SHOW_MESSAGE = _Paths.SHOW_MESSAGE;
  static const SHOW_DIFFUSION = _Paths.SHOW_DIFFUSION;
  static const DIFFUSION = _Paths.DIFFUSION;
  static const NETWORK = _Paths.NETWORK;
  static const APROPOS = _Paths.APROPOS;
  static const NOUSCONTACTEZ = _Paths.NOUSCONTACTEZ;
  static const SPLASH = _Paths.SPLASH;
  static const DISCUSSION = _Paths.DISCUSSION;
  static const SHOW_DISCUSSION = _Paths.SHOW_DISCUSSION;
  static const HISTORIQUE = _Paths.HISTORIQUE;
  static const SHOW_HISTORIQUE = _Paths.SHOW_HISTORIQUE;
  static const SHOW_INFORMATION = _Paths.SHOW_INFORMATION;
  static const PHARMACIE = _Paths.PHARMACIE;
  static const SHOW_PHARMACIE = _Paths.SHOW_PHARMACIE;
  static const ANNUAIRE = _Paths.ANNUAIRE;
  static const DEBUT = _Paths.DEBUT;
  static const ZOOM = _Paths.ZOOM;
  static const JOB = _Paths.JOB;
  static const COCAN = _Paths.COCAN;
  static const TRAJET = _Paths.TRAJET;
  static const HOTEL = _Paths.HOTEL;
  static const RESTAURANT = _Paths.RESTAURANT;
  static const BARS_MAQUIS = _Paths.BARS_MAQUIS;
  static const WIDGET_SPLASH_SCREEN = _Paths.WIDGET_SPLASH_SCREEN;
  static const SITETOURISTIQUES = _Paths.SITETOURISTIQUES;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const AUTH = '/auth';
  static const MESSAGE = '/message';
  static const CONDITION = '/condition';
  static const MES_MESSAGES = '/mes_messages';
  static const ALL_MESSAGES = '/all_messages';
  static const ADD_MESSAGE = '/add_message';
  static const EDIT_MESSAGE = '/edit_message';
  static const ALERTE = '/alerte';
  static const MES_ALERTES = '/mes_alertes';
  static const ALL_ALERTES = '/all_alertes';
  static const ADD_ALERTE = '/add_alerte';
  static const EDIT_ALERTE = '/edit_alerte';
  static const ACTUALITE = '/actualite';
  static const SHOW_ACTUALITE = '/show_actualite';
  static const SHOW_ALERTE = '/show_alerte';
  static const SHOW_MESSAGE = '/show_message';
  static const SHOW_AGENDA = '/show_agenda';
  static const SHOW_DIFFUSION = '/show_diffusion';
  static const AGENDA = '/agenda';
  static const COMMERCE = '/commerce';
  static const SHOW_COMMERCE = '/show_commerce';
  static const DIFFUSION = '/diffusion';
  static const NETWORK = '/network';
  static const APROPOS = '/apropos';
  static const NOUSCONTACTEZ = '/nouscontactez';
  static const SPLASH = '/splash';
  static const DISCUSSION = '/discussion';
  static const SHOW_DISCUSSION = '/show_discussion';
  static const HISTORIQUE = '/historique';
  static const SHOW_HISTORIQUE = '/show_historique';
  static const SHOW_INFORMATION = '/show_information';
  static const PHARMACIE = '/pharmacie';
  static const SHOW_PHARMACIE = '/show_pharmacie';
  static const ANNUAIRE = '/annuaire';
  static const DEBUT = '/debut';
  static const ZOOM = '/zoom';
  static const JOB = '/job';
  static const SHOW_JOB = '/show_job';
  static const COCAN = '/cocan';
  static const TRAJET = '/trajet';

  static const HOTEL = '/hotel';
  static const RESTAURANT = '/restaurant';
  static const BARS_MAQUIS = '/bars-maquis';
  static const WIDGET_SPLASH_SCREEN = '/widget-splash-screen';
  static const SITETOURISTIQUES = '/sitetouristiques';
}
